name: Build and publish Docker image

on:
  release:
    types: [published]
    
jobs:
  push_to_registry:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get release tag
        id: tag_name
        run: echo "SOURCE_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build image
        run: make publish DOCKER_REPOSITORY=${{ secrets.DOCKER_REPOSITORY }}